eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zipkin:
  baseUrl: http://localhost:9411/
management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      authentication-database: admin
#       username: root
#       password: "{cipher}967f1cdc06e76ef279f6cc732928061e2489870ddf94af13ca4ebdc7fa42f43d"


server:
  port=: 0

logging:
  level:
    root: INFO
